INSERT INTO PRODUCT_CATEGORY(CATEGORY_NAME) VALUES ('Books');
INSERT INTO PRODUCT_CATEGORY(CATEGORY_NAME) VALUES ('Coffee Mugs');
INSERT INTO PRODUCT_CATEGORY(CATEGORY_NAME) VALUES ('Mouse Pads');
INSERT INTO PRODUCT_CATEGORY(CATEGORY_NAME) VALUES ('Luggage Tags');